"""
SEO article model.

One row per daily-generated article used to build topical authority in
the Greater Montreal area for construction / renovation keywords.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampUpdateMixin


class SeoArticle(Base, TimestampUpdateMixin):
    """Blog/SEO article auto-generated by the daily cron."""

    __tablename__ = "seo_articles"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    # Identity
    slug: Mapped[str] = mapped_column(String(200), unique=True, index=True, nullable=False)
    locale: Mapped[str] = mapped_column(String(8), nullable=False, default="fr", index=True)

    # Content
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    meta_description: Mapped[str] = mapped_column(String(300), nullable=False)
    content_md: Mapped[str] = mapped_column(Text, nullable=False)
    excerpt: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # SEO
    keywords: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    target_city: Mapped[Optional[str]] = mapped_column(String(120), nullable=True)
    target_service: Mapped[Optional[str]] = mapped_column(String(120), nullable=True)

    # Lifecycle
    published: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True, index=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return f"<SeoArticle(id={self.id}, slug='{self.slug}', locale='{self.locale}')>"
